### ISSUE TITLE
Unsupported layer 'Conv2DTranspose'

### ISSUE THREAD

**Issue by TaeheeJeong** [uhfband/keras2caffe#18]
Please support 'Conv2DTranspose'
Traceback (most recent call last):
  File "convert.py", line 9, in <module>
    keras2caffe.convert(model, 'facades.prototxt', 'facades.caffemodel')
  File "../../keras2caffe/convert.py", line 383, in convert
    raise Exception('Unsupported layer type: '+layer_type)
Exception: Unsupported layer type: Conv2DTranspose

**Comment by mrgransky** [comment]
#24 #21 #17 are all missing!
has there already been any fix?
